######### Service Port Config #########
server:
  port: 8761

######### Eureka Server Config #########
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

######### Logging Level Config #########
logging:
  level:
    root: debug

######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
