######### Service Port Config #########
server:
  port: 8761

######### Logging Level Config #########
logging:
  level:
    root: info

######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true