######### Service Port Config #########
server:
  port: 0

######### Eureka Server Config #########
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

######### Logging Level Config #########
logging:
  level:
    root: debug

######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: *
  prometheus:
    metrics:
      export:
        enabled: true
        pushgateway:
          enabled: true
          address: ${PUSHGATEWAY_ADDRESS:http://localhost:9091}
          job: service-discovery
