global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'service-discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'service-discovery:8761'

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'config-server:8888'
