######### Service Port Config #########
server:
  port: 8888

######### Eureka Client Config #########
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://service-discovery:8761/eureka/}

######### Config Server Config #########
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codeJars/ecommerce_eda_config.git
          clone-on-start: false
          force-pull: true
          skip-ssl-validation: true
          timeout: 5


######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true

