######### Service Port Config #########
server:
  port: 8888

######### Eureka Client Config #########
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

######### Config Server Config #########
spring:
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_REPO}
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: false
          timeout: 10
          default-label: main

######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true

######### Micrometer Tracing config ##########
  tracing:
    sampling:
      probability: 0.1
    propagation:
      type: b3  # b3 header -> used by Zipkin, Brave (Spring's default)	X-B3-TraceId, X-B3-SpanId, X-B3-Sampled
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT}
