server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${CONFIG_SERVER_HOST:http://localhost:8761/eureka/}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codeJars/ecommerce_eda_config.git
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: false
          timeout: 10
          default-label: main

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics