server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codeJars/ecommerce_eda_config.git
          clone-on-start: false
          force-pull: true
          skip-ssl-validation: true
          timeout: 5

logging:
  level:
    root: debug

management:
  endpoints:
    web:
      exposure:
        include: *

