######### Service Port Config #########
server:
  port: 0

######### Eureka Client Config #########
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

######### Config Server Config #########
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codeJars/ecommerce_eda_config.git
          clone-on-start: true
          force-pull: true
          skip-ssl-validation: false
          timeout: 10
          default-label: main

######### Logging Level Config #########
logging:
  level:
    root: info

######### Prometheus Pushgateway Config #########
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, metrics
  prometheus:
    metrics:
      export:
        enabled: true
        pushgateway:
          enabled: true
          address: ${PUSHGATEWAY_ADDRESS}
          job: config-server